//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Classify.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ClassifyEntities : DbContext
    {
        public ClassifyEntities()
            : base("name=ClassifyEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Categorymaster> Categorymasters { get; set; }
        public virtual DbSet<Citymaster> Citymasters { get; set; }
        public virtual DbSet<Countrymaster> Countrymasters { get; set; }
        public virtual DbSet<Product> Products { get; set; }
        public virtual DbSet<Statemaster> Statemasters { get; set; }
        public virtual DbSet<User> Users { get; set; }
    }
}
