//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Classify.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.Web;

    public partial class Product
    {
        public int Id { get; set; }
        public Nullable<int> UserId { get; set; }
        [Required(ErrorMessage = "This Field is Required")]
        public string Name { get; set; }
        [Required(ErrorMessage = "This Field is Required")]
        public Nullable<int> Category { get; set; }
        [Required(ErrorMessage = "This Field is Required")]
        public Nullable<int> Code { get; set; }
        [Required(ErrorMessage = "This Field is Required")]
        public Nullable<decimal> Price { get; set; }
        [Required(ErrorMessage = "This Field is Required")]
        public string Description { get; set; }
        [Required(ErrorMessage = "This Field is Required")]
        public Nullable<bool> Status { get; set; }
        [Required(ErrorMessage = "This Field is Required")]
        public Nullable<int> Discount { get; set; }
        public string Image { get; set; }
        public Nullable<System.DateTime> Createddate { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }

        public virtual Categorymaster Categorymaster { get; set; }
        public virtual User User
        {
            get; set;

        }
        public HttpPostedFileBase ProductImg { get; set; }

    }
}
