//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Classify.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class User
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public User()
        {
            this.Products = new HashSet<Product>();
        }

        public int Id { get; set; }
        [MinLength(3, ErrorMessage = "Atleast 3 char needed")]
        [MaxLength(50, ErrorMessage = "upto 50 char allowed")]
        [Required(ErrorMessage = "This Field is Required")]
        public string Firstname { get; set; }
        [MinLength(3, ErrorMessage = "Atleast 3 char needed")]
        [MaxLength(50, ErrorMessage = "upto 50 char allowed")]
        [Required(ErrorMessage = "This Field is Required")]
        public string Lastname { get; set; }
        [MinLength(3, ErrorMessage = "Atleast 3 char needed")]
        [MaxLength(50, ErrorMessage = "upto 50 char allowed")]
        [Required(ErrorMessage = "This Field is Required")]
        [RegularExpression("^([a-zA-Z0-9_\\-\\.]+)@([a-zA-Z0-9_\\-\\.]+)\\.([a-zA-Z]{2,5})$", ErrorMessage = "Invalid email")]
        public string Email { get; set; }
        [RegularExpression("^\\d{10}$", ErrorMessage = "only digits length of 10 is allowed")]
        [Required(ErrorMessage = "This Field is Required")]
        public string Contactnumber { get; set; }
        [MinLength(20, ErrorMessage = "min 20 char needs")]
        [MaxLength(150, ErrorMessage = "max 150 char allowed")]
        [Required(ErrorMessage = "This Field is Required")]
        public string Address { get; set; }
        [Required(ErrorMessage = "This Field is Required")]
        public Nullable<int> City { get; set; }
        [Required(ErrorMessage = "This Field is Required")]
        public Nullable<int> State { get; set; }
        [Required(ErrorMessage = "This Field is Required")]
        public Nullable<int> Country { get; set; }
        [RegularExpression("^\\d{6}$", ErrorMessage = "Zip code should be 6 digits")]
        [Required(ErrorMessage = "This Field is Required")]
        public Nullable<int> Zipcode { get; set; }        
        [MinLength(10, ErrorMessage = "min 5 char needed")]
        [Required(ErrorMessage = "This Field is Required")]
        public string Password { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<bool> IsVerified { get; set; }
        public string VerificationTokken { get; set; }
        public Nullable<int> Otp { get; set; }
        public Nullable<System.DateTime> Createddate { get; set; }
        public Nullable<System.DateTime> Modifieddate { get; set; }
        public Nullable<System.DateTime> lastlogin { get; set; }
        public Nullable<bool> MailSent { get; set; }
    
        public virtual Citymaster Citymaster { get; set; }
        public virtual Countrymaster Countrymaster { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Product> Products { get; set; }
        public virtual Statemaster Statemaster { get; set; }
    }
}
